import type { Metadata } from "next";
import { Section, P, List, LI, Term } from "@/components/legal/prose";

export const metadata: Metadata = {
  title: "Data & Security",
  description:
    "The personal information CXNET holds, where it lives, and how it is protected.",
};

const EFFECTIVE = "June 24, 2026";

export default function DataPage() {
  return (
    <>
      <div className="mb-10">
        <h1 className="font-serif text-3xl text-text">Data &amp; Security</h1>
        <p className="mt-2 text-xs uppercase tracking-[0.16em] text-text-faint">
          Effective {EFFECTIVE}
        </p>
      </div>

      <Section index={1} title="Purpose of this notice">
        <P>
          This notice sits alongside the Privacy Policy and sets out, in plain
          terms, exactly what personal information CXNET holds, where it is
          stored, and the measures that keep it isolated to you. It is meant to
          be specific enough to answer a compliance or security question without
          having to ask.
        </P>
      </Section>

      <Section index={2} title="Personal data inventory">
        <P>The personal information CXNET holds falls into three groups:</P>
        <List>
          <LI>
            <Term>Identity.</Term> Email address and basic Google profile fields
            (name, avatar URL), plus a system-generated user identifier and your
            membership on the invitation allowlist.
          </LI>
          <LI>
            <Term>Financial records.</Term> Everything you enter: account names
            and balances, income and expense entries, investment positions,
            assets, liabilities, recurring rules, transfers, and reconciliation
            history, together with the currency and dates attached to each.
          </LI>
          <LI>
            <Term>Operational.</Term> Authentication session tokens (cookies) and
            standard server logs generated by hosting.
          </LI>
        </List>
        <P>
          We hold no payment-card numbers, no bank login credentials, and no
          government identifiers. CXNET never connects to your bank. Every
          figure is entered by you.
        </P>
      </Section>

      <Section index={3} title="Where it lives">
        <P>
          Identity and financial records are stored in a <Term>Supabase</Term>{" "}
          Postgres database. The application is hosted on <Term>Vercel</Term>.
          Market-price and exchange-rate lookups are made server-side to{" "}
          <Term>Yahoo Finance</Term> and <Term>frankfurter.dev</Term> and carry
          no personal information. Authentication is handled by Supabase Auth
          using Google as the identity provider.
        </P>
      </Section>

      <Section index={4} title="How your data is isolated">
        <List>
          <LI>
            <Term>Row Level Security.</Term> Every row in the database is tagged
            with its owner&rsquo;s user identifier, and database policies enforce
            that you can read or write only your own rows. This is the real
            backstop, enforced at the database, not merely in the application.
          </LI>
          <LI>
            <Term>Invitation allowlist.</Term> A database trigger rejects any
            sign-in whose email is not on the allowlist, so accounts cannot be
            self-created.
          </LI>
          <LI>
            <Term>Encryption in transit and at rest.</Term> All traffic uses
            TLS, and the database provider encrypts stored data at rest.
          </LI>
          <LI>
            <Term>Least exposure.</Term> Privileged keys stay server-side and are
            never shipped to the browser. Third-party market requests are proxied
            through auth-guarded server routes.
          </LI>
        </List>
      </Section>

      <Section index={5} title="Access">
        <P>
          Day-to-day, no one but you can see your records; row-level policies
          prevent it. The operator holds the administrative keys needed to run
          and repair the service and may access data only when necessary for
          maintenance, security, or a support request you have made. There is no
          analytics pipeline reading your financial data.
        </P>
      </Section>

      <Section index={6} title="Retention and deletion">
        <P>
          Your records persist while your account is active. On a deletion
          request we remove your profile and financial rows; because of
          row-level ownership, deleting your account removes the data tied to it.
          Provider backups age out on a rolling schedule. You can export your data
          at any time from Settings using <Term>Download my data</Term>, and you
          can request deletion at{" "}
          <a
            href="mailto:feitcarter@gmail.com"
            className="text-text underline decoration-border-strong underline-offset-4 transition hover:decoration-brass"
          >
            feitcarter@gmail.com
          </a>
          .
        </P>
      </Section>

      <Section index={7} title="Breach response">
        <P>
          If a security incident affecting your personal information occurs, we
          will investigate, take steps to contain it, and notify affected users
          and any required regulator without undue delay, consistent with our
          obligations under PIPEDA and, where applicable, the GDPR.
        </P>
      </Section>

      <Section index={8} title="Questions">
        <P>
          Security or data-handling questions are welcome at{" "}
          <a
            href="mailto:feitcarter@gmail.com"
            className="text-text underline decoration-border-strong underline-offset-4 transition hover:decoration-brass"
          >
            feitcarter@gmail.com
          </a>
          .
        </P>
      </Section>
    </>
  );
}
